rabbit= {'chessName': "兔子",
            'id':1,
            'race' : "mammal",
            'star' : 1,
            'attack' : 21,
            'attack_interval':0.9,
            'attack_range' : 1.5,
            'armor':7,
            'health':250}

ant = {'chessName' : "蚂蚁",
                         'id':2,
                         'race' : "insect",
                         'star' : 1,
                         'attack' : 20,
                         'attack_interval' : 1,
                         'attack_range' : 1.5,
                         'armor':10,
                         'health':180}

littleUglyFish = {'chessName' : "小丑鱼",
                         'id':3,
                         'race' : "marine",
                         'star' : 1,
                         'attack' : 30,
                         'attack_interval':0.9,
                         'attack_range' : 2,
                         'armor':13,
                         'health':216}
                

llama = {'chessName' : "羊驼",
                         'id':4,
                         'race' : "mammal",
                         'star' : 2,
                         'attack' : 40,
                         'attack_interval':1.1,
                         'attack_range' : 2,
                         'armor':13,
                         'health':410}
wolf = {'chessName' : "头狼",
                         'id':5,
                         'race' : "mammal",
                         'star' : 2,
                         'attack' : 45,
                         'attack_interval':0.85,
                         'attack_range' : 1.5, 
                         'armor':21,
                         'health':520}
ladybug = {'chessName' : "瓢虫",'id':6,
                         'race' : "insect",
                         'star' : 2,
                         'attack' : 21,
                         'attack_interval':0.8,
                         'attack_range' : 1.5,
                         'armor':25,
                         'health':478}
bee = {'chessName' : "蜜蜂",'id':7,
                         'race' : "insect",
                         'star' : 2,
                         'attack' : 36,
                         'attack_interval':1.1,
                         'attack_range' : 1.5,
                         'armor':20,
                         'health':380}
swallower = {'chessName' : "食人鱼",'id':8,
                         'race' : "marine",
                         'star' : 2,
                         'attack' : 88,
                         'attack_interval':1.2,
                         'attack_range' : 1.5,
                         'armor':20,
                         'health':380}
sea_hedgehog = {'chessName' : "海胆",'id':9,
                         'race' : "marine",
                         'star' : 2,
                         'attack' : 20,
                         'attack_interval':1.0,
                         'attack_range' : 1.5,
                         'armor':3,
                         'health':800}
heal_deer = {'chessName' : "麋鹿",'id':10,
                         'race' : "mammal",
                         'star' : 3,
                         'attack' : 30,
                         'attack_interval':1.05,
                         'attack_range' : 2.5,
                         'armor':27,
                         'health':830}
monkey = {'chessName' : "忍者猴",'id':11,
                         'race' : "mammal",
                         'star' : 3,
                         'attack' : 74,
                         'attack_interval':0.7, # 有可能太高
                         'attack_range' : 3,
                         'armor' : 17,
                         'health': 288}
hippo = {'chessName' : "犀牛",'id':12,
                         'race' : "mammal",
                         'star' : 3,
                         'attack' : 68,
                         'attack_interval':1.7,
                         'attack_range' : 1.5,
                         'armor' : 91,
                         'health': 1250}
bear = {'chessName' : "熊",'id':13,
                         'race' : "mammal",
                         'star' : 3,
                         'attack' : 95,
                         'attack_interval':0.95,
                         'attack_range' : 1.5,
                         'armor' : 45,
                         'health': 760}
butterfly = {'chessName' : "福蝶",'id':14,
                         'race' : "insect",
                         'star' : 3,
                         'attack' : 66,
                         'attack_interval':1.1,
                         'attack_range' : 3,
                         'armor' : 27,
                         'health': 518}
fireworm = {'chessName' : "萤火虫",'id':15,
                         'race' : "insect",
                         'star' : 3,
                         'attack' : 0,
                         'attack_interval':10,
                         'attack_range' : 2,
                         'armor' : 30,
                         'health': 650}
mantis = {'chessName' : "螳螂",'id':16,
                         'race' : "insect",
                         'star' : 3,
                         'attack' : 140,
                         'attack_interval':0.85,
                         'attack_range' : 1.5,
                         'armor' : 78,
                         'health': 270}
scorpion = {'chessName' : "蝎子",'id':17,
                         'race' : "insect",
                         'star' : 3,
                         'attack' : 58,
                         'attack_interval':1.5,
                         'attack_range' : 1.5,
                         'armor' : 32,
                         'health': 840}
anglerfish = {'chessName' : "灯笼鱼",'id':18,
                         'race' : "marine",
                         'star' : 3,
                         'attack' : 45,
                         'attack_interval':1.0,
                         'attack_range' : 2,
                         'armor' : 23,
                         'health': 470}
electric_eel = {'chessName' : "电鳗",'id':19,
                         'race' : "marine",
                         'star' : 3,
                         'attack' : 65,
                         'attack_interval':0.9,
                         'attack_range' : 3,
                         'armor' : 23,
                         'health': 560}
monoceros = {'chessName' : "一角鲸",'id':21,
                         'race' : "marine",
                         'star' : 3,
                         'attack' : 88,
                         'attack_interval':0.95,
                         'attack_range' : 1.5,
                         'armor' : 27,
                         'health': 680}
turtle = {'chessName' : "海龟",'id':22,
                         'race' : "marine",
                         'star' : 3,
                         'attack' : 50,
                         'attack_interval':1.0,
                         'attack_range' : 1.5,
                         'armor' : 81,
                         'health': 750}
elephant = {'chessName' : "大象",'id':23,
                         'race' : "mammal",
                         'star' : 4,
                         'attack' : 115,
                         'attack_interval':1.2,
                         'attack_range' : 2,
                         'armor' : 65,
                         'health': 1600}
tiger = {'chessName' : "老虎",'id':24,
                         'race' : "mammal",
                         'star' : 4,
                         'attack' : 150,
                         'attack_interval':0.7,
                         'attack_range' : 1.5,
                         'armor' : 43,
                         'health': 1040}
unicorn_b = {'chessName' : "独角仙", 'id':25,
                         'race' : "insect",
                         'star' : 4,
                         'attack' : 112, # 有点低
                         'attack_interval':0.55,
                         'attack_range' : 4,
                         'armor' : 26,
                         'health': 560}
spider = {'chessName' : "蜘蛛", 'id':26,
                         'race' : "insect",
                         'star' : 4,
                         'attack' : 98, # 有点低
                         'attack_interval':0.85,
                         'attack_range' : 1.5,
                         'armor' : 65,
                         'health': 1270}
octopus = {'chessName' : "章鱼",'id':27,
                         'race' : "marine",
                         'star' : 4,
                         'attack' : 99, # 有点低
                         'attack_interval':0.75,
                         'attack_range' : 2,
                         'armor' : 42,
                         'health': 1550}
shark = {'chessName' : "鲨鱼",'id':28,
                         'race' : "marine",
                         'star' : 4,
                         'attack' : 80, # 有点低
                         'attack_interval':0.5,
                         'attack_range' : 1.5,
                         'armor' : 60,
                         'health': 1200}
